littlekernel/lk

external/lib/heap/dlmalloc/dlmalloc.c
include/kernel/novm.h
include/kernel/vm.h
include/lib/page_alloc.h
kernel/novm/novm.c
kernel/vm/vm.c
lib/heap/cmpctmalloc/cmpctmalloc.c
lib/heap/miniheap/miniheap.c
lib/heap/page_alloc.c

Please take a look. Something like this is needed for newer Dartino's that need to know where the Dart heap is going to be allocated.

Add API used by Dartino to get arena list

---

lib/fs/spifs/spifs.c

With GCC 5.3.1 (5-2016-q2-update from https://launchpad.net/gcc-arm-embedded)
additional warnings about unused variables cause compilation to fail.

[spifs] Fix warning with GCC 5.3.1

---

arch/arm64/asm.S
arch/arm64/start.S
arch/arm64/thread.c

sp can become misaligned from 16 byte boundry because context frame
is not a multiple of 16 bytes.

[aarch64] Fix stack pointer misalignment

---

makefile

I had my external project directory named foo_lk, and this got me puzzled for a bit. Maybe this will save somebody else from the same issue.
My make-fu is not super strong, so please review with caution. (Also, hi, Travis!)

[make] Compare whole words for LKINC check.

---

dev/gpio_i2c/gpio_i2c.c
dev/gpio_i2c/rules.mk

If GPIO_I2C_PULLUPS == 1, enables pullups when not actively
driving I2C lines low.

[dev/gpio_i2c] add optional pullups

---

engine.mk
makefile

If some included rule.mk defines an additional make target that the user
might want to call (e.g., "flash"), and user specifies a project name on
the command line, then previously the outer "makefile" would call
engine.mk multiple times. The new logic prevents that.
Additionally, silence extra "Nothing to be done" messages when calling
engine.mk again after removing the project name from make goals.

[make] don't call build engine multiple times.

---

engine.mk
lib/version/rules.mk
make/build.mk

When lib/version was included, a rule depended on .PHONY.  This would
unexpectedly invoke other rules defined as dependent on .PHONY (standard
phony-ness signal).
As a side effect, this used to generate srcfiles.txt and
include_paths.txt in build dir. Since they are useful, we might always
build those anyway, and not make them phony at all.

[make] [lib/version] remove a misplaced .PHONY

---

lib/version/rules.mk

Without this, the rule that depends on the generated file
gets rebuilt every time.

[lib/version] add a level of .phony indirection

---

app/tests/cbuf_tests.c
app/tests/include/app/tests.h
app/tests/rules.mk
app/tests/tests.c
lib/cbuf/cbuf.c
lib/cbuf/include/lib/cbuf.h

Previously, if tail was == 0, and we wrote exactly enough bytes to
the end of the buffer, then head would end up at 0 as well. This
would make the buffer instaneously empty, as head == tail.

[lib/cbuf] [app/tests] fix off by one in lib/cbuf. add a test.

---

make/build.mk

Without the dependencies, the files get written once and don't get
updated when include paths or source files change.

[build] add deps for srcfiles.txt and include_paths.txt

---

lib/sysparam/sysparam.c

free hexbuffer in error path of hexstr_to_val()

[lib][sysparam] free hexbuffer in error path

---

arch/arm/arm/arch.c

just in case they are enabled by default.

[arch][arm] disable alignment aborts

---

platform/pc/include/platform/multiboot.h
platform/pc/platform.c

Several multiboot constants are off per the multiboot spec, leading to incorrect booting:
https://www.gnu.org/software/grub/manual/multiboot/multiboot.html

Fix two multiboot for x86

---

arch/x86/descriptor.c

In 64-bit mode, the TSS descriptor is expanded to 16 bytes.
Currently, high 32-bit of TSS base address is set to be zero.
Updte descriptor structure definition, add high 32-bit high adress
and reserved bit.
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>

[arch][x86] bug fix in TSS descriptor base address

---

lib/bio/bio.c

lib/bio/bio.c:345:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
Signed-off-by: Tristan Shieh <tristan.shieh@mediatek.com>

[lib][bio] fix compile warning with arch/arm64

---

platform/stm32f0xx/include/platform/timer_capture.h
platform/stm32f0xx/rules.mk
platform/stm32f0xx/timer_capture.c

Right now only capture is supported with the timers.  As more modes
are supported, the lower level bits of the driver should be
refactored.

[stm32f0xx] Add timer capture driver.

---

kernel/timer.c

Incredibly minor documentation comment change. The comment for `timer_set_periodic` mentioned a non-existent parameter `delay` rather than the `period` argument --- perhaps a copy+paste error from the doc comment for timer_set_oneshot!

(Very) minor documentation comment change to timer implementation.

---

platform/stm32f0xx/uart.c

The IRQ handler was being misdefined, so the correct ISR was not being
invoked.

[stm32f0xx] Fix UART3/4 interrupts

---

platform/mediatek/common/rules.mk
platform/mediatek/mt6735/debug.c
platform/mediatek/mt6735/include/platform/mt_gpt.h
platform/mediatek/mt6735/include/platform/mt_irq.h
platform/mediatek/mt6735/include/platform/mt_reg_base.h
platform/mediatek/mt6735/include/platform/mt_typedefs.h
platform/mediatek/mt6735/include/platform/mt_uart.h
platform/mediatek/mt6735/interrupts.c
platform/mediatek/mt6735/mt_gpt.c
platform/mediatek/mt6735/platform.c
platform/mediatek/mt6735/rules.mk
platform/mediatek/mt6735/timer.c
platform/mediatek/mt6735/uart.c
project/mt6735.mk
target/mt6735/init.c
target/mt6735/rules.mk

These set of patches were originated from platform and project mt6797 which commited by Mediatek.
According to the source release from vendor “Raindi Technology"(http://www.raindi.com.cn/), you can buy development board of mt6735 from Taobao (https://world.taobao.com/item/539050522155.htm) and get the reference SDK.
Hence I'm trying to port development board "Project: ap7350_65u_l1" of platform mt6735 from the following release back to mainline of little kernel.
http://git.huayusoft.com/tomsu/AP7350_MDK-kernel
https://github.com/alexgoussev/AP7350_MDK-kernel
While this board and the platform is a famous low-end product, to get support in the mainline little kernel will be good to all developers.

Project: add platform/target/project support of mt6735

---

arch/arm64/start.S

After a TLBI instruction the right thing to do is to execute DSB followed by ISB. DSB ensures that the TLBI is seen by all observers of the system and ISB ensures that the DSB has finished before continuing.

[arch][arm64] Fix barriers in startup code

---

arch/arm/arm/start.S

After a TLBI instruction the right thing to do is to execute DSB followed by ISB. DSB ensures that the TLBI is seen by all observers of the system and ISB ensures that the DSB has finished before continuing.
Also, the value in `<Rt>` is ignored for a TLBIALL. It isn't needed to load 0 to r12 and then use r12 in the instruction. In order not to cause confusion it is better to not load anything to r12.

[arch][arm] Fix execution of TLBIALL instructions

---

lib/bio/subdev.c

Sub device inherits parent device erase_byte.
Nand flash device is with erase_byte = 0xFF, but in bio_publish_subdevice,
the sub device erase_byte will be with initial value 0.
When the image with the chunk of 0, the chunk is not written, but the
read value is 0xFF.
Signed-off-by: Pibben <pibben.tung@mediatek.com>

[lib][bio] sub device inherits parent device erase_byte

---

external/platform/stm32f0xx/STM32F0xx_HAL_Driver/stm32f0xx_hal_pcd.c

Fixes a race in the STM USB driver which can lead to the device seeing only 0-length SETUP transfers. The bug ultimately leads to a failed USB enumeration. The race condition is described in further detail below.
The current behavior of the IRQ handler for received OUT transfers is as such:
- Clear RX_CTR bit (at this point, HW sees that SW has acknowledged previous SETUP/OUT transfer, and the HW will now accept new STATUS transfers)
- Call out to the client OutStageCallback (nothing significant here)
- Set EP_RX_CNT back to size of max_packet (was previously set to 0 as we expect to receive 0-length OUT transfer from host. HW uses this value to limit the amount of data it can receive)
- Set RX_STAT back to VALID (the HW can now receive new STATUS/OUT transfers)
The important thing to …

[stm32f0cube][bugfix] Fix race which leads to 0-length SETUP transfers

---

arch/arm/include/arch/defines.h
arch/arm/rules.mk
arch/arm/toolchain.mk
platform/tms570/rules.mk
project/tms570-launchpad.mk
target/tms570/rules.mk

* Adds target tms570-launchpad, for TI TMS570 Launchpad Dev Kit
(https://www.ti.com/store/ti/en/p/product/?p=LAUNCHXL2-TMS57012)
* Adds CPU definitions for Cortex R4F (BE) CPU, implementing
ARMv7-R ISA. Does not yet add definitions for ARMv7 arch entry
functions.
* Board does not yet build - platform.c/uart.c are empty, no GIC
entry points provided.

[platform][tms570-launchpad] Skeleton of port to TI LaunchXL2-TMS57012

---

make/macros.mk

The behavior of += has changed such that it will not prepend a space, if the original variable was empty. This breaks the generation of config.h. The fix I've found is to create the variable with two empty variables and a space between, and this seems to work for both Make 4.2 and 4.3.
Source: https://lwn.net/Articles/810071/
```
* WARNING: Backward-incompatibility!
Previously appending using '+=' to an empty variable would result in a value
starting with a space.  Now the initial space is only added if the variable
already contains some value.  Similarly, appending an empty string does not
add a trailing space.
```

Fix incompatibility with Make 4.3.

---

platform/stm32f0xx/include/platform/timer_capture.h
platform/stm32f0xx/timer_capture.c

As specified in ST reference manual RM0091, the prescaling factor
applied by timers is 1 plus the value in the corresponding prescaler
register. (See section 17.4.11 for TIM1, and analogous sections for
other timers.)
This change causes stm32_timer_capture_setup to take the prescaling
factor as input rather than the register value.

[stm32f0xx] Fix prescaler value.

---

arch/arm/arm/fpu.c

All shipping ARMv7-R processors include VFPv3-D16, a subset of VFPv3
with only 16 double-precision registers. The first -R profile CPU
with a complete VFP or NEON implementation is the Cortex-R52,
implementing ARMv8-R.
LK's context switch code had a dynamic check and would only save
d16-d31 if present, but gcc/gas will not assemble code that includes
references to d16-d31 when mcpu=cortex-r4f or other v7-R CPUs.
Ideally we'd key the #if off of __TARGET_FPU_VFPV3_D16, but that
only appears to be defined by the ARM compilers, not gcc. Use
V7-R as the key instead.

[platform][tms570-launchpad] Do not try to save d16-d31 on ARMv7-R

---

lib/libc/include/stdint.h

The name of the define provided by limits.h is USHRT_MAX not USHORT_MAX.

[libc] Fix UINT16_MAX definition.

---

lib/elf/elf.c
lib/elf/include/lib/elf_defines.h
lib/libc/string/rules.mk

[libc] allow arch string rules to be missing
[elf] add the constant for VC4

[libc] allow arch string rules to be missing

---

arch/x86/include/arch/x86/mmu.h

The issue was initially found on AMD machine when run lk with qemu kvm, it
can't boot if kvm hardware is enable in qemu.
According to Intel system programming guild Chapter 4 "Paging",
if the page table entry is non-leaf entry, then the G bit will be
ignored.
However, According to AMD programmer mannul Volume 2, Chapter 5.3
"Long-Mode Page Translation", the non-leaf page table entry G bit
must be zero.
The patch clears inner page table entry G bit to zero so that it
works on both Intel and AMD CPU

[arch][x86] Unset x86 inner page table entry G bit

---

arch/arm64/mp.c

[arch][arm64] unmask_interrupt needs the same numbers as register_int_handler

[arch][arm64] unmask_interrupt needs the same numbers as register_int_handler

---

arch/arm/arm/arch.c
arch/arm/arm/include/arch/aspace.h
arch/arm/arm/mmu.c

arch_mmu_map was failing hard, because the identity mapping does not fall within the `vmm_get_kernel_aspace`
this creates a new aspace covering the loader, so it can identity map
linux is also unable to use the FPU if lazy FPU context switching had turned it off prior to the chainload, `arm_fpu_set_enable()` is used to turn it back on

[arch][arm] improve arm chainload

---

arch/arm64/asm.S
arch/arm64/start.S

It is possible for early initialization functions such as lk_main()
to contain NEON instructions because we don't build the kernel with
-mgeneral-regs-only. As a result we can end up taking an FPU exception
before we are ready to handle it.
We didn't have this problem when starting at a higher exception level
than EL1 because we turned off FPU traps in arm64_elX_to_el1(). But we
neglected to do so when starting at EL1. Fix the problem by moving the
CPACR_EL1 manipulation out of arm64_elX_to_el1() and into arm_reset().

[arch][arm64] disable EL1 FPU traps even when starting at EL1

---

arch/arm64/start.S
platform/qemu-virt-arm/secondary_boot.S
scripts/do-qemuarm

If we were booted at EL2 (e.g. when passing -machine
virt,virtualization=on), we need to use SMC instead of HVC for PSCI
calls. Change psci_call() to do this and add a flag to do-qemuarm to
allow testing this scenario.

[arch][arm64] use SMC when booted at EL2 in QEMU

---

arch/arm64/include/arch/asm_macros.h
arch/arm64/start.S

Add cache clean + invalidate on the page tables that get modified during
startup before the MMU is enabled. Without this, if these memory regions
were present in cache before LK started, the CPU will see the stale
cached values as soon as the MMU is enabled. Invalidating these forces
the CPU to fetch the correct values from memory after the MMU is enabled.

[arch][arm64] cache maintainance on page tables during boot

---

arch/arm64/include/arch/arm64/mmu.h
arch/arm64/mmu.c
arch/arm64/start.S

Change the early startup code to set TCR_EL1.IPS to
ID_AA64MMFR0_EL1.PARange if it has a defined value (the currently
defined values have the same meanings), but use 48-bit PAs if 52-bit
PAs are supported because 52-bit PAs have a different translation
table format that we don't support. Stash the computed TCR_EL1 in a
variable and use it in the context switch code.

[arch][arm64] determine the correct TCR_EL1.IPS at runtime

---

dev/bus/pci/backend/type1.cpp

It should invoke type1_read_byte() rather than type1_read_half().

[dev][bus][pci] fixed type1_read_byte API bug

---

lib/gfx/gfx.c

all places that call flush, check if its null before calling it
but its never actually written to, so it can sometimes point to garbage and just fault

[lib][gfx] fix undefined flush pointer

---

platform/qemu-virt-riscv/plic.c

Old PLIC_PRIORITY macro had an off-by-one bug, causing you to set the priority for the wrong IRQ.

[platform] [riscv-virt] Fix PLIC_PRIORITY macro

---

.github/workflows/notify-irc.yml

I just noticed that pushing to my fork sent messages to IRC - this could be quite spammy, so restrict this action to the main repository.

Don't notify IRC on pushes to forks

---

arch/arm64/mmu.c

Precisely set bits [55:22] of the vaddress in bits [43:0] for the vae1is and vaee1is TLBI commands.
On platforms where FEAT_TLL is implemented, bits [47:44] of the command accept a TTL parameter which can optionally be set to hint the translation table level containing the address being invalidated. Implementations aren't architecturally required to perform the invalidation if the hint is incorrect however. Invalidations may therefore fail with the current implementation if the vaddress has bits set in [58:55].
This is notably an issue on ARM fastmodels which doesn't perform the invalidation when the TTL parameter is incorrect.

[arch][arm64] Fix mmu_unmap issue when FEAT_TTL is implemented

---

lib/libc/string/strncpy.c

The wrong placement of the increment for index `i` causes an unexpected behavior, which the `strncpy` writes an extra '\0'.
For example:
The `src` string is "abc". The buffer size of `dest` is 5.
When we call `strncpy(dest, src, 5)`, the first `for` loop copies the characters, 'a', 'b', and 'c', to the `dest[0:2]`. In the 4th iteration, however, the `for` loop breaks due to the termination of `src` whereas the value of `i` stays 3. At the moment, it has copied 4 bytes, including the '\0' of `src`.
In the second `for` loop, we have `i = 3` and `count = 5`, so the loop copies two more '\0' to the `dest`. As a result, the `strncpy` copies 6 bytes to the `dest` buffer, leading to buffer overflow.
Fix the issue by increasing the index `i` before every copy.

[libc][string] fix strncpy potential buffer overflow

---

engine.mk
make/module.mk

Certain projects may want to prevent the usage of certain modules from being used. Here are two examples of when this may occur:
1. The Project has it's own fdt library and does not want developer's using the version of libfdt included with LK
2. The project does not want developers using mincrypt.
`DENY_MODULES` is a list which developers can set in their own project makefiles which is checked on each module inclusion. If that module is on the deny list, it causes a build failure.

[make] Add ability to deny modules from being used

---

lib/io/console.c
lib/io/include/lib/io.h

Introduces a flag which allows a project to disable the default output to platform_dputc. This is useful is the project wants to maintain `platform_dputc` for panic conditions but otherwise use a registered callback for console io.
Change-Id: I1362529a6bb40d191ac3f7c6069985c371d9284c

[console] Flag to disable default console output

---

lib/heap/heap_wrapper.c

argv[] should have at least 3 elements because argv[2] is accessed in line 345.

[lib][heap] Fix array index out-of-range

---

app/tests/include/app/tests.h
app/tests/rules.mk
app/tests/tests.c
app/tests/v9p_tests.c
dev/virtio/9p/client.c
dev/virtio/9p/include/dev/virtio/9p.h
dev/virtio/9p/protocol.c
dev/virtio/9p/protocol.h
dev/virtio/9p/rules.mk
dev/virtio/9p/virtio-9p.c
dev/virtio/virtio.c
platform/qemu-virt-arm/rules.mk
scripts/do-qemuarm

Hi @travisg,
As we discussed in #398, I uploaded the commits to support VirtIO 9p devices. I tested it with arm platform and it worked just fine. I let it attach the `lk/` directory as the shared dir and read the `LICENSE` file. Please see the log bellow:
```
initializing apps
starting app inetsrv
starting internet servers
starting app shell
entering main console loop
] v9p_tests
0x80013c08: 2f 2a 0a 20 2a 20 43 6f 70 79 72 69 67 68 74 20 |/*. * Copyright
0x80013c18: 28 63 29 20 32 30 30 38 2d 32 30 31 35 20 54 72 |(c) 2008-2015 Tr
0x80013c28: 61 76 69 73 20 47 65 69 73 65 6c 62 72 65 63 68 |avis Geiselbrech
0x80013c38: 74 0a 20 2a 0a 20 2a 20 50 65 72 6d 69 73 73 69 |t. *. * Permissi
0x80013c48: 6f 6e 20 69 73 20 68 65 72 65 62 79 20 67 72 61 |on is hereby gra
0x80013c58: 6e 74 65 64 2c …
```

[virtio][9p] Add VirtIO 9p device driver

---

lk.code-workspace

This change updates lk.code-workspace to specify
* editor.detectIndentation as false, as otherwise that overrides the desired editor.tabSize setting.
* editor.insertSpaces as true, since spaces are preferred over tabs.
* editor.formatOnSave as false for C and C++ files, as - in the absence of a .clang-format file - the clangd extension is likely to default to choices that don't respect the local style.

[vscode] Update workspace file to better respect local style

---

lib/console/console.c

This change updates the `help` console command to list the available commands alphabetically, but only when we're not panicking. This makes `help`'s helping more helpful, which is pretty helpful as far as help goes.

[console] List commands alphabetically by name in normal mode

---

.gitignore
docs/getting_started.md
scripts/fetch-toolchains.py

This change introduces $LK_ROOT/toolchains as an official installation directory for toolchains, as well as a new script for conveniently installing them there. getting_started.md is updated to suggest its use.

[scripts] Introduce scripts/fetch-toolchains.py

---

kernel/port.c

port_group_remove() used to return without unlocking a thread if no matching read port is found, which is not correct. This patch adds a call to THREAD_UNLOCK before it returns ERR_BAD_HANDLE.

[kernel][port] add a missing THREAD_UNLOCK call in port_group_remove()

---

arch/arm64/arch.c
arch/arm64/asm.S
arch/arm64/include/arch/arm64.h
dev/interrupt/arm_gic/arm_gic_common.h
dev/interrupt/arm_gic/gic_v3.c

Refering Zircon's 'gic_init' function, enable ARE and Group 1 added.
For arm_generic_timer configuration, 'arm64_get_boot_el' and 'arm64_is_kernel_in_hyp_mode' added to make decision for the hypervisor/virtual timer irq.

[arch][arm] Enable distributor with ARE, group 1

---

arch/riscv/include/arch/riscv.h
arch/riscv/include/arch/riscv/feature.h
dev/bus/pci/debug.cpp
external/lib/heap/dlmalloc/dlmalloc.c
lib/libcpp/include/type_traits

I noticed a few warnings while building RISC-V with LLVM 17, this PR should fix them.

Various minor warning fixes for RISC-V Clang builds

---

lib/uefi/boot_service_provider.cpp
lib/uefi/runtime_service_provider.cpp
lib/uefi/switch_stack.S
lib/uefi/switch_stack.h
lib/uefi/uefi.cpp

GCC 14 is quite picky about warnings, probably more so than clang.
-Fix a bunch of printf warnings. Pointers should be printed with %p. -Move some stuff into an anonymous namespace.
-Worked around GCC really not liking reinterpret_casting from one function pointer type to another. Fiddled with it a bit and eventually settled on casting the function pointer to const void * and passing it through.

[lib][uefi] fix a few warnings and a little code tidying

---

lib/uefi/uefi.cpp

Mediatek hit `table->number_of_table_entries` isn't initialized

[lib][uefi] initialize uefi system table with zeroes

---

lib/heap/miniheap/miniheap.c

For LK_DEBUGLEVEL > 1
> alloc_struct_begin_size: 24
> free_heap_chunk_size: 24
size: max(alloc_struct_begin_size, free_heap_chunk_size)
But when freeing the chunk, allocated size is expected to be greater than size of free_heap_chunk struct.
It contradicts its own code.
So add >= instead of > to maintain the integrity between allocation and freeing of memory chunk.

[lib][miniheap] fix: modify the assert condition in miniheap

---

lib/libc/atoi.c

Make `atol()` more robust and compatible with gclib's implementation that
1. accepts leading whitespace
2. accepts leading '+' character
3. handles overflow
Similar adjustments should be made to `atoul` and `atoull`.
I wasn't able to run this project's test suite and since my own (closed source)
project only covers `atol` (see tests in comment), I did not want to
touch anything but this function.

atol handles overflow and accepts leading whitespace and '+'

---

docs/fvp-base/how_to_run.md
docs/fvp-base/internal.md
platform/fvp-base/debug.c
platform/fvp-base/include/platform/fvp-base.h
platform/fvp-base/include/platform/gic.h
platform/fvp-base/platform.c
platform/fvp-base/rules.mk
project/fvp-base-test.mk
project/target/fvp-base.mk
target/fvp-base/include/target/debugconfig.h
target/fvp-base/rules.mk

Add initial support of FVP Base platform, supported peripherals:
* Arm Virtual Timer
* GICv2
* UART
uart0 log: [log.txt](https://github.com/user-attachments/files/20028953/log.txt)

Add FVP Base support

---

.github/workflows/github-ci-clang.yml
lib/uefi/uefi.cpp
scripts/unittest.py

This function was previously put in anon namespace, making it unavailable for other source files to consume. Since we made this function an API for consumption, move outside anon namespace so that linkers can find it.

[lib][uefi] Make load_pe_file extern linkage

---

kernel/include/kernel/thread.h
lib/libc/errno.c

Before this change, errno was "completely un-threadsafe" as the comment states.
This changes errno to be threadsafe by making errno a thread local variable.

[lib][libc] Make errno thread safe using TLS APIs

---

lib/uefi/boot_service_provider.cpp
lib/uefi/boot_service_provider.h
lib/uefi/include/uefi/protocols/efi_timestamp_protocol.h
lib/uefi/uefi_platform.cpp
lib/uefi/uefi_platform.h

Reads the ARM64-specific counter registers.
This only works on ARM64 platform obviously, which is the only platform we support for UEFI at the moment.

[lib][uefi] Implement EFI_TIMESTAMP_PROTOCOL

---

lib/uefi/boot_service_provider.cpp
lib/uefi/configuration_table.cpp
lib/uefi/debug_support.cpp
lib/uefi/debug_support.h
lib/uefi/rules.mk
lib/uefi/uefi.cpp

I implemented the UEFI Specification version 2.10, specifically focusing on
the functionality described in Section 18.4, which details the EFI Debug
Support Table feature. This implementation ensures support for
hardware-assisted debugging and provides a standardized mechanism for
debuggers to discover and interact with system-level debug resources.

Add UEFI Debug Support Protocol

---

lib/uefi/blockio2_protocols.cpp
lib/uefi/blockio_protocols.cpp
lib/uefi/boot_service_provider.cpp
lib/uefi/configuration_table.cpp
lib/uefi/debug_support.cpp
lib/uefi/memory_protocols.cpp
lib/uefi/memory_protocols.h
lib/uefi/uefi_platform.cpp
lib/uefi/uefi_platform.h

This allows OEMs to customize exactly how their memories are allocated. For examples, OEMs might want to allocate certain parts of the UEFI from high address kernel space, for ease of access in LK world. Since UEFI spec requires everything to be identity mapped, the default implementation of memory allocation is identity mapped.

[lib][uefi] Move several memory APIs to uefi_platform.cpp

---

lib/uefi/memory_protocols.cpp

LTRACEF already outputs function name, no need to do it again

[lib][uefi] Fix LTRACEF logging

---

lib/uefi/charset.cpp
lib/uefi/charset.h
lib/uefi/rules.mk
lib/uefi/runtime_service_provider.cpp
lib/uefi/uefi.cpp
lib/uefi/variable_mem.cpp
lib/uefi/variable_mem.h

GBL needs to read an UEFI variable called "gbl_debug".
We add 2 commands. "uefi_set_var" to set an UEFI variable. And
"uefi_list_var" to list the UEFI variables.
For GBL, we can use "uefi_set_var gbl_debug 1" to enable its
debug mode.

lib: uefi: implement volatile UEFI variables

---

arch/arm/system-onesegment.ld
arch/arm/system-twosegment.ld
arch/arm64/system-onesegment.ld
arch/m68k/linker.ld
arch/microblaze/linker.ld
arch/mips/linker.ld
arch/or1k/linker.ld
arch/riscv/linker-onesegment.ld
arch/riscv/linker-twosegment.ld
arch/x86/32/kernel.ld
arch/x86/64/kernel.ld

Using wild match init_array* to include global array init ctor
Before:
10 .ctors             00000040 ffff0000001e6b80 00000000401e6b80 DATA
11 .dtors             00000000 ffff0000001e6bc0 00000000401e6bc0 DATA
12 .got               00000060 ffff0000001e6bc0 00000000401e6bc0 DATA
13 .init_array.1      00000470 ffff0000001e6c20 00000000401e6c20
14 .fini_array.1      00000470 ffff0000001e7090 00000000401e7090
15 .dummy_post_data   00000000 ffff0000001e7500 00000000401e7500 DATA
16 .bss               00009460 ffff0000001e8000 00000000401e8000 BSS
After:
10 .ctors             000004b0 ffff0000001e6b80 00000000401e6b80 DATA
11 .dtors             00000470 ffff0000001e7030 00000000401e7030
12 .got               00000060 ffff0000001e74a0 00000000401e74a0 DATA
13 .dummy_post_data   00000000 …

fix link script not include global array init

---

app/tests/port_tests.c
kernel/port.c

port_create() has a known race condition in name reservation because of the separation of name uniqueness validation and name addition.  This pull request adds a test that verifies the race is reachable, fixes the race, and updates the test with slight changes to support it.

port_create race test and fix
