.gitignore
=> [gitignore] remove cscope.out

include/stdlib.h, lib/libc/rules.mk, lib/libc/strtol.c, lib/libc/strtoll.c, lib/libm/e_atan2.c, lib/libm/e_exp.c, lib/libm/e_fmod.c, lib/libm/e_log.c, lib/libm/rules.mk, lib/libm/s_atan.c, lib/libm/s_ceil.c, lib/libm/s_round.c, lib/libm/s_trunc.c
This adds some additional libc/libm functionality from BSD.
=> [lib] Import some libc/libm functions from BSD.

platform/stm32f7xx/qspi.c
Spiflash operations should be atomic. Guard external qspi methods with a mutex.
=> [spiflash][stm32f7] Protect SPIFlash driver with a mutex.

include/pow2.h, platform/stm32f0xx/can.c, platform/stm32f0xx/include/platform/can.h, platform/stm32f0xx/rules.mk
=> Stm32f0xx CAN Support.

platform/stm32f0xx/can.c, platform/stm32f0xx/debug.c, platform/stm32f0xx/dma.c, platform/stm32f0xx/init.c, platform/stm32f0xx/spi.c, platform/stm32f0xx/timer.c, target/nucleo-f072rb/init.c
Sending the pull request seperatly from the commit that removes the StdPeriph_Lib.
=> Make stm32f0xx platform full native.

platform/mediatek/common/gic/include/mt_gic.h, platform/mediatek/common/gic/mt_gic_v3.c, platform/mediatek/common/gic/rules.mk, platform/mediatek/common/include/sync_write.h, platform/mediatek/common/rules.mk, platform/mediatek/mt6797/debug.c, platform/mediatek/mt6797/include/platform/mt_gpt.h, platform/mediatek/mt6797/include/platform/mt_irq.h, platform/mediatek/mt6797/include/platform/mt_reg_base.h, platform/mediatek/mt6797/include/platform/mt_typedefs.h, platform/mediatek/mt6797/include/platform/mt_uart.h, platform/mediatek/mt6797/interrupts.c, platform/mediatek/mt6797/mt_gpt.c, platform/mediatek/mt6797/platform.c, platform/mediatek/mt6797/rules.mk, platform/mediatek/mt6797/timer.c, platform/mediatek/mt6797/uart.c, platform/mediatek/rules.mk, project/mt6797.mk, target/mt6797/init.c, target/mt6797/rules.mk
Initial support for mediatek mt6797 platform.
- basic driver: uart, timer, gicv3
- uart is polled
- fix incompatible license in sync_write.h
=> [platform][mediatek] support mediatek platform: mt6797

lib/gfx/gfx.c
Simple fractal routine added to gfx command line options.
=> [gfx] Add mandelbrot test to gfx routines

app/tests/thread_tests.c, include/kernel/event.h, kernel/event.c, lib/cbuf/include/lib/cbuf.h, platform/cc13xx/radio.c
Switch from the UK spelling of signalling (also, signalled and
signaller) to the American spelling.
=> [spelling] signalling --> signaling

lib/console/console.c
I found that I wanted a simple way to run the same command repeatedly. Maybe this is useful for other people as well?
=> [lib/console] add "repeat" command.

kernel/thread.c
if NUM_PRIORITIES < 32, result will be negative?
=> [kernel] fix get top thread error if NUM_PRIORITIES < 32

make/build.mk
Produce .map file at link time, useful to debug position of symbols, sections, etc
=> [make] output .map file

arch/arm/stackusage
Just use parentheses in prints
=> [arch][arm] stackusage python3 compatibility

platform/bcm28xx/include/platform/bcm28xx.h, platform/bcm28xx/include/platform/mailbox.h, platform/bcm28xx/mailbox.c, platform/bcm28xx/platform.c, platform/bcm28xx/rules.mk, project/rpi3-test.mk
Framebuffer driver for Raspberry Pi.  Implements basic mailbox driver and messages for retrieving framebuffer address from VideoCore
=> [bcm][gfx] gfx driver for raspberry pi

kernel/vm/pmm.c
Bug fix of PAGE_ADDRESS_FROM_ARENA in pmm of vm module
Signed-off-by: James Zhong <sha8312@gmail.com>
=> [kernel][vm][pmm] Bug fix in pmm

platform/stm32f0xx/i2c.c
We need to look at the TC status bit to know that a transaction has ended.
This has the added benefit of cleaning up REG and TX handling.
=> [stm32f0xx] Fix i2c stop and repeated start handling.

kernel/port.c
make_buf() is a static function with two callers that pass in one of
two constants. The parameters allowed for any uint count to be
supplied and the arithmetic during memory allocation is unchecked.
This change updates make_buf() prototype to reflect its usage, which is
safe, while eliminating any future uses from accidentally becoming
unsafe. It does so by changing the parameter as a boolean that decides
between a big or a small port buffer.
=> kernel/port.c: make make_buf() safe

platform/stm32f0xx/exti.c
A bunch of the register access here didn't match STM's docs.  The old
code had a few bugs:
1) The EXTI4-15 handler would clear pending bits for interrupts 16-31.
2) GPIO interrupt configuration was very misindexed.
=> [stm32f0xx] Correct register access for EXTI controller

dev/interrupt/arm_gic/arm_gic.c, platform/amlogic-s912d/include/platform/gic.h, platform/amlogic-s912d/include/platform/s912d.h, platform/amlogic-s912d/platform.c, platform/amlogic-s912d/rules.mk, platform/amlogic-s912d/uart.c, project/vim2-test.mk, target/vim2/README, target/vim2/rules.mk
Basic support for VIM2
Tested on both VIM2 and qemu. 
Added support for GIC SPI based on Fuchsia gic-v2 code
=> Initial support for Khadas VIM2 boards

external/platform/stm32f0xx/CMSIS/inc/stm32f0xx.h, platform/stm32f0xx/can.c, platform/stm32f0xx/gpio.c, platform/stm32f0xx/include/platform/exti.h, platform/stm32f0xx/include/platform/gpio.h, platform/stm32f0xx/rules.mk, platform/stm32f0xx/timer_capture.c, platform/stm32f0xx/uart.c, platform/stm32f0xx/vectab.c
This cleans up handling of a lot of optional components
across f0xx models.
=> Add stm32f070 support

external/platform/nrf52/include/platform/nrf52xxx.h, platform/nrf52xxx/rules.mk, platform/nrf52xxx/uart.c, project/nrf52-pca10056-test.mk, project/target/nrf-pca10056.mk, target/nrf-pca10056/include/target/debugconfig.h, target/nrf-pca10056/include/target/gpioconfig.h, target/nrf-pca10056/init.c, target/nrf-pca10056/rules.mk
Support for nrf52840 which adds some capabilities over nrf52832 which is already supported.
Target and project for Nordic pca10056 dev kit also included.
=> [nrf] Support for NRF52840 DK

arch/x86/64/exceptions.S, arch/x86/64/mmu.c, arch/x86/gdt.S
Bug Fix:
1. Fix bug when update mapping in kernel aspace
Enhanced feature:
1. Update TSS selector description
2. Enlarge TSS selector up to SMP_MAX_CPUS
3. Enlarge interrupt numbers support to 0xFF in arch x86-64
=> [arch][x86] Bug fix and feature enhancement

kernel/thread.c
This change ensures that during thread scheduling
only needed cores are woken up as per the thread's
CPU affinity rather than all cores. This would avoid
un-necessary wakup for other cores from lower power
states without having to execute anything.
Signed-off-by: vannapurve <vannapurve@google.com>
=> [kernel][thread] Wake up only needed cores

lib/fdtwalk/fdtwalk.c
=> [fdtwalk] Fix a bug in #address-cells parsing

lib/libc/atof.c, lib/libc/include/stdlib.h, lib/libc/rules.mk
I ported atof function from https://github.com/GaloisInc/minlibc repo, i edited it according to code style of LK.
=> [libc] add atof() function

arch/arm/arm-m/systick/systick.c, kernel/debug.c, kernel/include/kernel/thread.h, kernel/thread.c
Hi Travis, please review and see which are suitable for upstream. Feel free to provide feedback or reject any that aren't suitable.
=> Candidates for upstream

external/lib/lwip/core/tcp_in.c
Applied patch for CVE-2004-0230 in tcp_in.c which prevents RST Spoofing Attack (Denial of Service).
=> Fix CVE-2004-0230

lib/fs/test.c, lib/libc/include/stdio.h, lib/libc/stdio.c
Implement stdio file io APIs with LK lib/fs APIs
Signed-off-by: Chieh-Min Wang <cmwang@google.com>
=> [lib][stdio] wrap file io APIs with stdio APIs

README.md
Fixes: https://github.com/littlekernel/lk/issues/426
=> Document how to use clang in README

lib/uefi/boot_service_provider.cpp, lib/uefi/boot_service_provider.h, lib/uefi/include/uefi.h, lib/uefi/relocation.cpp, lib/uefi/rules.mk, lib/uefi/runtime_service_provider.cpp, lib/uefi/uefi_platform.cpp, lib/uefi/uefi_platform.h
1. ResetSystem protocol
2. ExitBootService
=> Implement 2 missing UEFI protocols

lib/console/console.c
Launch a thread to execute commands when the last argument is ampersand
=> [console] support background command execution

lib/uefi/debug_support.cpp
This commit refactors teardown_debug_support() to make the code looks simpler.
=> lib: uefi: debug_support.cpp: fix code-style of teardown_debug_support()

docs/gdb_debug_support_for_gbl.md
Adding a document for how to debug GBL with UEFI debug support protocol.
=> [docs] add debug support for GBL doc
